# Generated by Django 5.0.1 on 2024-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
