# Generated by Django 5.0.1 on 2024-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='client_zip_code',
            new_name='client_zipcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='full_weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='making_charge',
        ),
        migrations.RemoveField(
            model_name='item',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stone_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='item',
            name='vat_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
