# Generated by Django 5.0.1 on 2024-01-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='making_charges',
            field=models.DecimalField(decimal_places=2, default=11.11, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='making_charges_percentage',
            field=models.DecimalField(decimal_places=2, default=11.11, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=11.11, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='stone_price',
            field=models.DecimalField(decimal_places=2, default=11.11, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=11.11, max_digits=6),
            preserve_default=False,
        ),
    ]
