# Generated by Django 5.0.1 on 2024-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_item_making_charges_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_weight',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
