# Generated by Django 5.0.1 on 2024-01-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoice_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='jewel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='metal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stone_weight',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='wastage',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
