# Generated by Django 5.0.1 on 2024-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_item_jewel_item_metal_item_stone_weight_item_wastage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
