# Generated by Django 5.0.1 on 2024-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
