# Generated by Django 5.0.1 on 2024-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
    ]
